
services:

  db:
    image: mysql:8
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Run DB initialization script
    networks:
      - wp

  wordpress:
    image: wordpress:latest
    #build: ./wordpress
    #container_name: wordpress_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes: ["./html:/var/www/html"]
    #volumes:
    #  - ./wordpress/wp-content:/var/www/html/wp-content  # Mount custom themes and plugins
    networks:
      - wp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - wp

networks:
  wp:

volumes:
  db_data: